site_name: Cema
site_url: https://arthursw.github.io/cema/
repo_url: https://github.com/arthursw/cema
repo_name: arthursw/cema
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # features:
  #   - navigation.expand
extra:
  version:
    provider: mike

nav:
  - Overview: index.md
  - Getting started: getting_started.md
  - Advanced example: advanced_example.md
  - Code Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            members_order: source
            summary:
              attributes: false
              functions: true
  - mike:
      alias_type: symlink

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
