name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-

      - name: Install uv
        run: pip install uv

      - name: Install docs dependencies
        run: uv pip install ".[docs]" --system

      - name: Get gh-pages branch
        run: git fetch origin gh-pages --depth=1

      - name: Set version default
        run: uv run mike set-default 1.0
      
      - name: Deploy version with mike (update gh-pages branch and push it)
        run: mike deploy --push --update-aliases 1.0 latest